### ISSUE TITLE
Missing 'typings install' in README

### ISSUE THREAD

**Issue by berezovskyi** [jiemakel/khepri#2]
I had to run this as well to start serving the page.

**Comment by jiemakel** [comment]
Gotta love the node ecosystem. `tsd install` was how this was done at the time this code was created, but maybe after the migration to `typings` this has broken down with newer dependencies (and now we've moved already from `typings` to `npm`).

I went ahead and updated the whole build ecosystem for this project. Everything seems to work for me now.
